version: '3'
services:
    forntend: 
        build: frontend
        ports: 
            - "4200:4200"
        container_name: fornt-container
        restart: always
    backend:
        build: backend
        ports: 
            - "3000:3000"
        container_name: back-container
        restart: always
        links: 
            - database
    database:
        build: database
        container_name: db-container
        restart: always
        environment: 
            - MYSQL_ROOT_PASSWORD=P@$$w0rd
        volumes: 
            - /root/docker/database/conf.d:/etc/mysql/
        